### ISSUE TITLE
Validate desired network states

### ISSUE THREAD

**Issue by atanasdinov** [suse-edge/nm-configurator#10]
The following example is a completely valid desired state for nmstate:
```
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.122.250
      prefix-length: 24
    enabled: true
  ipv6:
    address:
    - ip: 2001:db8::1:1
      prefix-length: 64
    enabled: true
```

However, since it is missing a MAC address for the interface, host mapping will not be properly generated which in turn would make applying the configuration fail:

```
$ cat _out/host_config.yaml
- hostname: node1
  interfaces: []
```
