### ISSUE TITLE
openvswitch not working properly

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/nm-configurator#113]
Related to https://github.com/nmstate/nmstate/pull/2801 which adds support for trunk vlan ports in ovenvswitch bridge.
However this change is not required to demonstrate this bug.

Using the following `node1.yaml` config 
```yaml
interfaces:
  - name: eth0
    type: ethernet
    state: up
    mac-address: 5c:c7:c9:5e:fb:ec
  - bridge:
      port:
        - name: br0-10
          vlan:
            mode: access
            tag: 10
        - name: eth0
          vlan:
            mode: access
            tag: 10
    description: ovs bridge with vlans
    name: br0
    state: up
    type: ovs-bridge
  - name: br0-10
    state: up
    type: ovs-interface
    ipv4:
      enabled: true
      dhcp: false
      address:
        - ip: 172.16.1.1
          prefix-length: 24
    ipv6:
      enabled: false
```

NMC generates the following `host_config.yaml`:
```yaml
- hostname: node1
  interfaces:
  - logical_name: br0
    interface_type: ovs-bridge
  - logical_name: eth0
    mac_address: 5c:c7:c9:5e:fb:ec
    interface_type: ethernet
  - logical_name: br0-10
    interface_type: ovs-interface
```

And the following nmconnection files for node1:
- br0-10-if.nmconnection
- br0-10-port.nmconnection
- br0-br.nmconnection
- eth0-port.nmconnection
- eth0.nmconnection

Applying this with NMC leads to the following error:

> [2024-10-10T17:49:23Z INFO  nmc::apply_conf] Identified host: node1
> [2024-10-10T17:49:23Z INFO  nmc::apply_conf] Set hostname: node1
> [2024-10-10T17:49:23Z INFO  nmc::apply_conf] Processing interface 'br0'...
> [2024-10-10T17:49:23Z ERROR nmc] Applying config failed: Copying connection files: Reading file: No such file or directory (os error 2)

There is a mismatch between the listed interfaces in `host_config.yaml` and the nmconnection files.
