### ISSUE TITLE
Configuring 802.1x certificates

### ISSUE THREAD

**Issue by koendelaat** [suse-edge/nm-configurator#89]
To use 802.1x Network Access Control we need to provision the appropriate certificates for each node.

- Is it currently possible to configure 802.1x on a interface (I assume yes, given it's part of the nmstate interface config) ?
- How to configure / deploy the certificates on each node (in combination with Edge Image Builder)?

I found the following example how a `nmstate` file could look like:
```yaml
interfaces:
- name: enp1s0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 24
    dhcp: false
  ipv6:
    enabled: false
  802.1x:
    ca-cert: /etc/pki/tls/certs/ca.crt
    client-cert: /etc/pki/tls/certs/client.crt
    eap-methods:
      - tls
    identity: client.example.org
    private-key: /etc/pki/tls/private/client.key
    private-key-password: password
``` 

If possible, can you give a working example configuration?
